Repository kube-burner/kube-burner, pull requests merged in 2023-06, with the labels that each got.

#327 Docs reorg
  README.md
  cmd/kube-burner/kube-burner.go
  docs/ci.md
  docs/cli.md
  docs/configuration.md
  docs/contributing.md
  docs/css/extra.css
  docs/development/index.md
  docs/development/linters.md
  docs/index.md
  docs/indexers.md
  docs/measurements.md
  docs/media/demo.gif
  docs/metrics.md
  docs/observability/alerting.md
  docs/observability/index.md
  docs/observability/indexing.md
  docs/observability/metrics.md
  docs/ocp.md
  docs/reference/configuration.md
  mkdocs.yml
  pkg/alerting/alert_manager.go
  pkg/prometheus/types.go
  pkg/util/metrics/metrics.go
  pkg/workloads/helpers.go
Labels: enhancement

#336 Update CI to run different workloads for commit/PR/release
  .github/workflows/builders.yml
  .github/workflows/commit.yml
  .github/workflows/docs.yml
  .github/workflows/gorelease.yml
  .github/workflows/image-upload.yml
  .github/workflows/kube-burner.yml
  .github/workflows/linters.yml
  .github/workflows/pullrequest.yml
  .github/workflows/release.yml
  .github/workflows/test-k8s.yml
  .pre-commit-config.yaml
  LICENSE
  docs/development/ci.md
  docs/development/ci/commit.md
  docs/development/ci/pullrequest.md
  docs/development/ci/release.md
  docs/development/ci/tests.md
  docs/development/ci/workflow-graph.md
  docs/measurements.md
  docs/observability/indexing.md
  docs/ocp.md
  docs/reference/configuration.md
  mkdocs.yml
  test/.gitignore
  test/base.sh
  test/helpers.bash
  test/kube-burner.yml
  test/run-ocp.sh
  test/run.sh
  test/test-k8s.bats
  test/test-ocp.bats
Labels: enhancement

#353 Update release event
  .github/workflows/docs.yml
  .github/workflows/release.yml
  docs/development/ci.md
  docs/development/ci/pullrequest.md
  docs/development/ci/release.md
  docs/development/ci/workflow-graph.md
Labels: bug

#354 Fix very small typos
  docs/cli.md
  docs/measurements.md
  docs/observability/index.md
  docs/observability/metrics.md
  docs/ocp.md
  docs/reference/configuration.md
Labels: documentation

#352 Reporting mode for OCP wrapper
  cmd/kube-burner/kube-burner.go
  cmd/kube-burner/ocp-config/cluster-density-ms/cluster-density-ms.yml
  cmd/kube-burner/ocp-config/cluster-density-v2/cluster-density-v2.yml
  cmd/kube-burner/ocp-config/cluster-density/cluster-density.yml
  cmd/kube-burner/ocp-config/metrics-report.yml
  cmd/kube-burner/ocp-config/node-density-cni/node-density-cni.yml
  cmd/kube-burner/ocp-config/node-density-heavy/node-density-heavy.yml
  cmd/kube-burner/ocp-config/node-density/node-density.yml
  cmd/kube-burner/ocp.go
  docs/development/ci.md
  docs/measurements.md
  docs/observability/metrics.md
  docs/ocp.md
  docs/reference/configuration.md
  go.mod
  go.sum
  pkg/burner/job.go
  pkg/config/config.go
  pkg/measurements/pod_latency.go
  pkg/measurements/pprof.go
  pkg/measurements/types/types.go
  pkg/measurements/vmi_latency.go
  pkg/prometheus/prometheus.go
  pkg/prometheus/types.go
  pkg/util/metrics/metrics.go
  pkg/util/metrics/utils.go
  pkg/workloads/helpers.go
  pkg/workloads/node-density-heavy.go
  test/helpers.bash
  test/k8s/kube-burner-delete.yml
  test/k8s/kube-burner-index-multiple-endpoint.yml
  test/k8s/kube-burner-index-single-endpoint.yml
  test/k8s/kube-burner.yml
  test/test-k8s.bats
  test/test-ocp.bats
Labels: enhancement

#357 Checkout before setup
  .github/workflows/builders.yml
  .github/workflows/gorelease.yml
  .github/workflows/image-upload.yml
Labels: bug

#359 Add aggregated workers memory utilization and remove memory total/ava…
  cmd/kube-burner/ocp-config/metrics-aggregated.yml
  cmd/kube-burner/ocp-config/metrics.yml
Labels: enhancement

#341 Support cluster scoped resources broadly
  docs/reference/configuration.md
  pkg/burner/create.go
  pkg/burner/delete.go
  pkg/burner/patch.go
  pkg/burner/utils.go
  pkg/burner/waiters.go
  pkg/config/config.go
  pkg/config/types.go
  test/k8s/kube-burner-crd.yml
Labels: enhancement

#363 Fetch PR commit in linters
  .github/workflows/pullrequest.yml
  .github/workflows/test-k8s.yml
  pkg/burner/create.go
  pkg/burner/delete.go
  pkg/burner/patch.go
  pkg/burner/utils.go
  test/.gitignore
  test/test-ocp.bats
Labels: bug

#368 Add ocpMajorVersion field
  docs/ocp.md
  go.mod
  go.sum
  pkg/burner/metadata.go
  pkg/measurements/pod_latency.go
  pkg/measurements/vmi_latency.go
  pkg/workloads/helpers.go
  test/helpers.bash
Labels: enhancement

#364 Start namespace names from 0
  cmd/kube-burner/ocp-config/cluster-density-ms/cluster-density-ms.yml
  cmd/kube-burner/ocp-config/cluster-density-v2/cluster-density-v2.yml
  cmd/kube-burner/ocp-config/cluster-density/cluster-density.yml
  cmd/kube-burner/ocp-config/node-density-cni/node-density-cni.yml
  cmd/kube-burner/ocp-config/node-density-heavy/node-density-heavy.yml
  pkg/burner/create.go
  pkg/burner/job.go
  pkg/burner/namespaces.go
  pkg/burner/patch.go
  pkg/burner/pre_load.go
  test/test-ocp.bats
Labels: bug
