Repository kube-burner/kube-burner, pull requests merged in 2023-12, with the labels that each got.

#525 New web-burner ocp wrapper
  cmd/kube-burner/ocp-config/web-burner-cluster-density/cluster_density_configmap.yml
  cmd/kube-burner/ocp-config/web-burner-cluster-density/cluster_density_dep_served.yml
  cmd/kube-burner/ocp-config/web-burner-cluster-density/cluster_density_dep_served_ports.yml
  cmd/kube-burner/ocp-config/web-burner-cluster-density/cluster_density_pod_served.yml
  cmd/kube-burner/ocp-config/web-burner-cluster-density/cluster_density_pod_service.yml
  cmd/kube-burner/ocp-config/web-burner-cluster-density/cluster_density_pod_service_ports.yml
  cmd/kube-burner/ocp-config/web-burner-cluster-density/cluster_density_secret.yml
  cmd/kube-burner/ocp-config/web-burner-cluster-density/web-burner-cluster-density.yml
  cmd/kube-burner/ocp-config/web-burner-init/adminPolicyBasedExternalRoute.yml
  cmd/kube-burner/ocp-config/web-burner-init/cm_frr.yml
  cmd/kube-burner/ocp-config/web-burner-init/macvlan_network.yml
  cmd/kube-burner/ocp-config/web-burner-init/permissionsClusterRole.yml
  cmd/kube-burner/ocp-config/web-burner-init/permissionsClusterRoleBinding.yml
  cmd/kube-burner/ocp-config/web-burner-init/permissionsRoleBinding.yml
  cmd/kube-burner/ocp-config/web-burner-init/permissionsServiceAccount.yml
  cmd/kube-burner/ocp-config/web-burner-init/pod_served.yml
  cmd/kube-burner/ocp-config/web-burner-init/pod_serving.yml
  cmd/kube-burner/ocp-config/web-burner-init/pod_serving_no_bfd.yml
  cmd/kube-burner/ocp-config/web-burner-init/pod_serving_single.yml
  cmd/kube-burner/ocp-config/web-burner-init/sriov_network.yml
  cmd/kube-burner/ocp-config/web-burner-init/web-burner-init.yml
  cmd/kube-burner/ocp-config/web-burner-node-density/node_density_pod_served.yml
  cmd/kube-burner/ocp-config/web-burner-node-density/node_density_pod_service_served.yml
  cmd/kube-burner/ocp-config/web-burner-node-density/web-burner-node-density.yml
  cmd/kube-burner/ocp.go
  docs/ocp.md
  pkg/workloads/types.go
  pkg/workloads/web-burner.go
Labels: enhancement

#502 Add network-policy workload
  docs/reference/configuration.md
  go.mod
  go.sum
  pkg/burner/job.go
  pkg/config/types.go
  pkg/util/template.go
Labels: documentation, enhancement

#536 Fix unsafe access to labels map to avoid a panic
  pkg/burner/create.go
Labels: bug

#533 Maintain original object's namespace when specified
  cmd/kube-burner/kube-burner.go
  docs/cli.md
  docs/reference/configuration.md
  pkg/burner/create.go
  pkg/burner/job.go
  pkg/burner/metadata.go
  pkg/burner/namespaces.go
  pkg/burner/pre_load.go
  pkg/burner/waiters.go
  pkg/measurements/pod_latency.go
  pkg/util/metrics/utils.go
  pkg/workloads/index.go
  test/helpers.bash
  test/k8s/kube-burner.yml
  test/k8s/objectTemplates/deployment.yml
  test/k8s/objectTemplates/pod.yml
  test/test-k8s.bats
Labels: enhancement

#545 Remove bats run
  .github/workflows/test-k8s.yml
  test/helpers.bash
  test/k8s/kube-burner-delete.yml
  test/test-k8s.bats
  test/test-ocp.bats
Labels: bug
