Repository kube-burner/kube-burner, pull requests merged in 2024-09, with the labels that each got.

#689 Fix golangci-lint precommit hook
  .golangci.yml
  .pre-commit-config.yaml
  cmd/kube-burner/kube-burner.go
  pkg/alerting/alert_manager.go
  pkg/burner/create.go
  pkg/burner/job.go
  pkg/burner/read.go
  pkg/burner/waiters.go
  pkg/measurements/service_latency.go
  pkg/util/template.go
  pkg/workloads/helpers.go
Labels: bug

#692 Direct Support for wait Option for ArgoCD Applications in Kube-Burner
  docs/reference/configuration.md
  go.mod
  go.sum
  pkg/burner/waiters.go
  pkg/config/types.go
  test/helpers.bash
  test/k8s/kube-burner.yml
  test/test-k8s.bats
Labels: enhancement

#699 Rename vmi latency measurement metrics
  pkg/measurements/pod_latency.go
  pkg/measurements/service_latency.go
  pkg/measurements/vmi_latency.go
Labels: bug, enhancement
