Repository kube-burner/kube-burner, pull requests merged in 2024-11, with the labels that each got.

#726 [GH#683] fix: absolute file paths interpreted as urls
  pkg/util/url_reader.go
  test/test-k8s.bats
Labels: bug

#714 Add support for sequential handling on Patch jobs and objects
  docs/reference/configuration.md
  pkg/burner/patch.go
  pkg/config/types.go
  test/helpers.bash
  test/k8s/kube-burner-sequential-patch.yml
  test/k8s/objectTemplates/deployment_patch_label.yaml
  test/test-k8s.bats
Labels: enhancement

#729 Reuse runJob for Delete and Read
  docs/reference/configuration.md
  pkg/burner/create.go
  pkg/burner/delete.go
  pkg/burner/job.go
  pkg/burner/patch.go
  pkg/burner/read.go
  pkg/burner/utils.go
  pkg/config/types.go
  test/k8s/kube-burner-sequential-patch.yml
Labels: enhancement

#737 Copy the labels to the underlying template even if it does not have any
  pkg/burner/utils.go
Labels: bug

#717 Decrease object verify logging level
  pkg/burner/utils.go
Labels: enhancement

#716 New PodReadyToStartContainers condition to pod_latency measurement
  docs/measurements/index.md
  pkg/measurements/pod_latency.go
  test/helpers.bash
Labels: enhancement

#727 Add method to import custom template rendering functions
  docs/wrappers/wrappers.md
  mkdocs.yml
  pkg/util/template.go
Labels: enhancement

#739 Optimize waiters
  kube-burner-virt.yml
  pkg/burner/consts.go
  pkg/burner/create.go
  pkg/burner/delete.go
  pkg/burner/executor.go
  pkg/burner/job.go
  pkg/burner/object.go
  pkg/burner/patch.go
  pkg/burner/pre_load.go
  pkg/burner/read.go
  pkg/burner/types/types.go
  pkg/burner/utils.go
  pkg/burner/waiters.go
Labels: bug, enhancement
