Repository kube-burner/kube-burner, pull requests merged in 2024-01, with the labels that each got.

#566 Pass the indexer instance to NewPrometheusClient
  cmd/kube-burner/kube-burner.go
  pkg/burner/job.go
  pkg/prometheus/prometheus.go
  pkg/prometheus/types.go
  pkg/util/metrics/metrics.go
  pkg/util/metrics/utils.go
  pkg/workloads/helpers.go
  pkg/workloads/index.go
Labels: enhancement

#572 Adding maximum aggregated memory metrics
  cmd/kube-burner/ocp-config/metrics-report.yml
Labels: enhancement

#573 Switch to Google's uuid module
  cmd/kube-burner/kube-burner.go
  cmd/kube-burner/ocp.go
  go.mod
  go.sum
  pkg/config/config.go
Labels: bug

#583 Set waitNs in each iteration
  pkg/burner/waiters.go
Labels: bug

#581 Update CI documentation
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
  docs/contributing/index.md
  docs/contributing/pullrequest.md
  docs/contributing/release.md
  docs/contributing/tests.md
  mkdocs.yml
Labels: documentation

#577 [WIP] Implement read jobType to simulate load with GET requests
  docs/index.md
  docs/reference/configuration.md
  pkg/burner/job.go
  pkg/burner/read.go
  pkg/config/config.go
  pkg/config/types.go
  test/k8s/kube-burner-read.yml
  test/test-k8s.bats
Labels: documentation, enhancement

#584 Permit basic authentication in metrics endpoint
  docs/cli.md
  pkg/prometheus/types.go
  pkg/util/metrics/metrics.go
  pkg/workloads/helpers.go
Labels: enhancement

#516 Service latency measurement
  cmd/kube-burner/kube-burner.go
  docs/measurements.md
  docs/observability/metrics.md
  go.mod
  go.sum
  hack/build_service_checker.sh
  pkg/burner/create.go
  pkg/burner/delete.go
  pkg/burner/job.go
  pkg/burner/namespaces.go
  pkg/burner/patch.go
  pkg/burner/pre_load.go
  pkg/burner/utils.go
  pkg/measurements/factory.go
  pkg/measurements/metrics/watcher.go
  pkg/measurements/pod_latency.go
  pkg/measurements/pprof.go
  pkg/measurements/service_latency.go
  pkg/measurements/types/types.go
  pkg/measurements/util/svc_checker.go
  pkg/measurements/vmi_latency.go
  pkg/util/namespaces.go
  pkg/util/utils.go
  test/k8s/kube-burner-delete.yml
  test/k8s/kube-burner.yml
  test/k8s/objectTemplates/pod.yml
  test/k8s/objectTemplates/service.yml
  test/test-k8s.bats
Labels: documentation, enhancement
