Repository kube-burner/kube-burner, pull requests merged in 2024-12, with the labels that each got.

#759 go-commons v1.0.18
  go.mod
  go.sum
Labels: enhancement

#748 New Job Type - Kubevirt
  docs/reference/configuration.md
  examples/workloads/kubevirt-power/kubevirt-power.yml
  examples/workloads/kubevirt-power/templates/vm-ephemeral.yml
  go.mod
  go.sum
  pkg/burner/delete.go
  pkg/burner/executor.go
  pkg/burner/job.go
  pkg/burner/kubevirt.go
  pkg/burner/object.go
  pkg/burner/patch.go
  pkg/burner/read.go
  pkg/config/types.go
  pkg/util/utils.go
  test/k8s/kube-burner-virt-operations.yml
  test/test-k8s.bats
Labels: documentation, enhancement

#745 Vmi latency fixes
  docs/measurements/index.md
  go.mod
  go.sum
  pkg/measurements/common.go
  pkg/measurements/vmi_latency.go
  test/k8s/kube-burner-virt.yml
Labels: bug, enhancement
