Repository kube-burner/kube-burner, pull requests merged in 2024-02, with the labels that each got.

#582 Replace deprecated bats-action
  .github/workflows/test-k8s.yml
Labels: bug

#586 Remove indexer from workload config
  pkg/workloads/helpers.go
  pkg/workloads/types.go
Labels: bug, enhancement

#588 Node 20 in GHA
  .github/workflows/builders.yml
  .github/workflows/docs.yml
  .github/workflows/gorelease.yml
  .github/workflows/image-upload.yml
  .github/workflows/test-k8s.yml
Labels: CI

#590 Garbage collect pods in default namespace
  test/k8s/kube-burner.yml
  test/test-k8s.bats
Labels: CI, optimization

#593 Make measurement indexing not a blocking operation
  cmd/kube-burner/kube-burner.go
  docs/measurements.md
  pkg/burner/create.go
  pkg/burner/job.go
  pkg/measurements/factory.go
  pkg/measurements/pod_latency.go
  pkg/measurements/pprof.go
  pkg/measurements/service_latency.go
  pkg/measurements/types/types.go
  pkg/measurements/vmi_latency.go
  pkg/prometheus/prometheus.go
  pkg/prometheus/types.go
  pkg/util/namespaces.go
Labels: optimization

#585 Cluster health check
  cmd/kube-burner/kube-burner.go
  docs/cli.md
  docs/reference/configuration.md
  examples/workloads/cluster-density/cluster-density.yml
  pkg/config/types.go
  pkg/util/cluster_health.go
  test/test-k8s.bats
Labels: enhancement
