Repository kube-burner/kube-burner, pull requests merged in 2025-06, with the labels that each got.

#873 Add developers meeting info to doc
  GOVERNANCE.md
Labels: documentation

#875 Public methods
  pkg/alerting/alert_manager.go
  pkg/measurements/base_measurement.go
  pkg/measurements/datavolume_latency.go
  pkg/measurements/job_latency.go
  pkg/measurements/node_latency.go
  pkg/measurements/pod_latency.go
  pkg/measurements/pvc_latency.go
  pkg/measurements/snapshot_latency.go
  pkg/measurements/vmi_latency.go
  pkg/workloads/helpers.go
Labels: bug

#881 Fix network policy measurement
  cmd/kube-burner/kube-burner.go
  pkg/burner/job.go
  pkg/measurements/base_measurement.go
  pkg/measurements/base_measurement_factory.go
  pkg/measurements/datavolume_latency.go
  pkg/measurements/factory.go
  pkg/measurements/job_latency.go
  pkg/measurements/netpol_latency.go
  pkg/measurements/node_latency.go
  pkg/measurements/pod_latency.go
  pkg/measurements/pprof.go
  pkg/measurements/pvc_latency.go
  pkg/measurements/service_latency.go
  pkg/measurements/snapshot_latency.go
  pkg/measurements/vmi_latency.go
Labels: bug

#860 [RFE] Per job garbage collection feature
  docs/reference/configuration.md
  pkg/burner/create.go
  pkg/burner/delete.go
  pkg/burner/executor.go
  pkg/burner/job.go
  pkg/burner/kubevirt.go
  pkg/burner/namespaces.go
  pkg/burner/patch.go
  pkg/burner/pre_load.go
  pkg/burner/read.go
  pkg/burner/utils.go
  pkg/burner/waiters.go
  pkg/config/config.go
  pkg/config/types.go
  test/k8s/kube-burner.yml
  test/test-k8s.bats
Labels: enhancement
