Repository kube-burner/kube-burner, pull requests merged in 2025-01, with the labels that each got.

#757 Preload vm images
  pkg/burner/pre_load.go
  test/k8s/kube-burner-virt.yml
  test/k8s/kube-burner.yml
Labels: enhancement

#764 Support running shell scripts from the embedded filesystem
  pkg/burner/job.go
  pkg/util/bash.go
Labels: bug, enhancement

#783 Fix metric and alerting profile reads in embedded directories
  pkg/alerting/alert_manager.go
  pkg/prometheus/prometheus.go
  pkg/util/url_reader.go
Labels: bug

#782 Update to golang 1.23
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/builders.yml
  .github/workflows/gorelease.yml
  .github/workflows/image-upload.yml
Labels: enhancement
